version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./www:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - php-fpm
    working_dir: /var/

  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm.docker
    volumes:
      - ./www:/var/www
      - ./docker/php/default.ini:/usr/local/etc/php/conf.d/default.ini
    depends_on:
      - mysql
    working_dir: /var/www

  mysql:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=yiitube
    restart: always
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DB: app
      ADMINER_PASSWORD: secret
      ADMINER_SERVER: mysql
      ADMINER_USERNAME: root
